[tool.poetry]
name = "22-1"
version = "1"
description = "flask-greet-calc"
authors = ["AJ <skyhighzed@gmail.com>"]
readme = "README.md"
packages = [{include = "22"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
